name: Jekyll site CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Витягти код
        uses: actions/checkout@v2

      - name: Налаштувати Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Встановити залежності
        run: npm install

      - name: Збудувати проект
        run: npm run build  # Замініть на вашу команду збірки

      - name: Розгорнути на GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout gh-pages
          cp -r dist/* .
          git add .
          git commit -m "Розгорнути на GitHub Pages"
          git push
